services:
  wearwine-db:
    container_name: wearwine--local
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: wearwine

    volumes:
      - pgdata:/var/lib/postgresql/data

    logging:
      driver: none

volumes:
  pgdata: