/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    tags: Tag;
    colors: Color;
    sizes: Size;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    sizes: SizesSelect<false> | SizesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'pdp-static': PdpStatic;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'pdp-static': PdpStaticSelect<false> | PdpStaticSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  googleId?: string | null;
  isVerified?: boolean | null;
  roles: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  type: 'hero' | 'carousel' | 'product';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug?: string | null;
  description?: string | null;
  category: number | Category;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  tags?: (number | Tag)[] | null;
  price: number;
  salePrice?: number | null;
  variants?:
    | {
        color: number | Color;
        size: number | Size;
        sku?: string | null;
        stock?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  name: string;
  hex?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes".
 */
export interface Size {
  id: number;
  label: string;
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (HeroBlock | CollectionGallery | DepthDeckCarousel | ProductListSection | ContactBlock)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  properties?: {
    paddingTop?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingTopMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottom?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottomMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    backgroundColor?: ('primary' | 'secondary' | 'alt') | null;
    backgroundColorMobile?: ('primary' | 'secondary' | 'alt') | null;
  };
  slides: {
    image: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionGallery".
 */
export interface CollectionGallery {
  properties?: {
    paddingTop?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingTopMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottom?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottomMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    backgroundColor?: ('primary' | 'secondary' | 'alt') | null;
    backgroundColorMobile?: ('primary' | 'secondary' | 'alt') | null;
  };
  images: {
    image: number | Media;
    title: string;
    label: string;
    gridClass: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'collectionGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DepthDeckCarousel".
 */
export interface DepthDeckCarousel {
  properties?: {
    paddingTop?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingTopMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottom?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottomMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    backgroundColor?: ('primary' | 'secondary' | 'alt') | null;
    backgroundColorMobile?: ('primary' | 'secondary' | 'alt') | null;
  };
  cards: {
    image: number | Media;
    title?: string | null;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'depthDeckCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductListSection".
 */
export interface ProductListSection {
  properties?: {
    paddingTop?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingTopMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottom?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottomMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    backgroundColor?: ('primary' | 'secondary' | 'alt') | null;
    backgroundColorMobile?: ('primary' | 'secondary' | 'alt') | null;
  };
  tagline: string;
  titlePrefix: string;
  titleHighlight: string;
  description: string;
  buttonText: string;
  /**
   * Maximum number of products to fetch
   */
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productListSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  properties?: {
    paddingTop?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingTopMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottom?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    paddingBottomMobile?:
      | (
          | 'NONE'
          | 'SM1'
          | 'SM2'
          | 'SM3'
          | 'MD1'
          | 'MD2'
          | 'MD3'
          | 'LG1'
          | 'LG2'
          | 'LG3'
          | 'XL1'
          | 'XL2'
          | 'XL3'
          | 'XXL1'
          | 'XXL2'
          | 'XXL3'
        )
      | null;
    backgroundColor?: ('primary' | 'secondary' | 'alt') | null;
    backgroundColorMobile?: ('primary' | 'secondary' | 'alt') | null;
  };
  badge: string;
  title: string;
  description: string;
  methods?:
    | {
        type: 'Email' | 'Phone' | 'Live Chat' | 'Support Hours';
        value: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'Instagram' | 'Twitter' | 'LinkedIn' | 'Facebook';
        href: string;
        id?: string | null;
      }[]
    | null;
  newsletter: {
    title: string;
    description: string;
    buttonText: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'sizes';
        value: number | Size;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  googleId?: T;
  isVerified?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  tags?: T;
  price?: T;
  salePrice?: T;
  variants?:
    | T
    | {
        color?: T;
        size?: T;
        sku?: T;
        stock?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  name?: T;
  hex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        collectionGallery?: T | CollectionGallerySelect<T>;
        depthDeckCarousel?: T | DepthDeckCarouselSelect<T>;
        productListSection?: T | ProductListSectionSelect<T>;
        contact?: T | ContactBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  properties?:
    | T
    | {
        paddingTop?: T;
        paddingTopMobile?: T;
        paddingBottom?: T;
        paddingBottomMobile?: T;
        backgroundColor?: T;
        backgroundColorMobile?: T;
      };
  slides?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionGallery_select".
 */
export interface CollectionGallerySelect<T extends boolean = true> {
  properties?:
    | T
    | {
        paddingTop?: T;
        paddingTopMobile?: T;
        paddingBottom?: T;
        paddingBottomMobile?: T;
        backgroundColor?: T;
        backgroundColorMobile?: T;
      };
  images?:
    | T
    | {
        image?: T;
        title?: T;
        label?: T;
        gridClass?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DepthDeckCarousel_select".
 */
export interface DepthDeckCarouselSelect<T extends boolean = true> {
  properties?:
    | T
    | {
        paddingTop?: T;
        paddingTopMobile?: T;
        paddingBottom?: T;
        paddingBottomMobile?: T;
        backgroundColor?: T;
        backgroundColorMobile?: T;
      };
  cards?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductListSection_select".
 */
export interface ProductListSectionSelect<T extends boolean = true> {
  properties?:
    | T
    | {
        paddingTop?: T;
        paddingTopMobile?: T;
        paddingBottom?: T;
        paddingBottomMobile?: T;
        backgroundColor?: T;
        backgroundColorMobile?: T;
      };
  tagline?: T;
  titlePrefix?: T;
  titleHighlight?: T;
  description?: T;
  buttonText?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  properties?:
    | T
    | {
        paddingTop?: T;
        paddingTopMobile?: T;
        paddingBottom?: T;
        paddingBottomMobile?: T;
        backgroundColor?: T;
        backgroundColorMobile?: T;
      };
  badge?: T;
  title?: T;
  description?: T;
  methods?:
    | T
    | {
        type?: T;
        value?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcementBar?: {
    text?: string | null;
    isActive?: boolean | null;
  };
  navItems?:
    | {
        link?: (number | null) | Page;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyright?: string | null;
  columns?:
    | {
        title?: string | null;
        links?:
          | {
              link?: (number | null) | Page;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdp-static".
 */
export interface PdpStatic {
  id: number;
  shipping: {
    title: string;
    description: string;
  };
  returns: {
    title: string;
    description: string;
  };
  trustBadges?:
    | {
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  sizeGuide: {
    title: string;
    description: string;
  };
  sizeChart: {
    image: number | Media;
    description: string;
  };
  cta: {
    addToCart: string;
    buyNow: string;
    addedToCart: string;
    outOfStock: string;
  };
  accordions?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo: number | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  socialLinks?:
    | {
        platform: 'Instagram' | 'Twitter' | 'LinkedIn' | 'Facebook';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        text?: T;
        isActive?: T;
      };
  navItems?:
    | T
    | {
        link?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyright?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdp-static_select".
 */
export interface PdpStaticSelect<T extends boolean = true> {
  shipping?:
    | T
    | {
        title?: T;
        description?: T;
      };
  returns?:
    | T
    | {
        title?: T;
        description?: T;
      };
  trustBadges?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  sizeGuide?:
    | T
    | {
        title?: T;
        description?: T;
      };
  sizeChart?:
    | T
    | {
        image?: T;
        description?: T;
      };
  cta?:
    | T
    | {
        addToCart?: T;
        buyNow?: T;
        addedToCart?: T;
        outOfStock?: T;
      };
  accordions?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}